FROM node
MAINTAINER jaga santagostino <hassanomar4700@gmail.com>

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json app/ /usr/src/app
RUN npm install
COPY app/ /usr/src/app

ENV NODE_ENV development

EXPOSE 8000
CMD ["npm", "start"]
